import tensorflow as tf            # import tensorflow
with tf.device("/gpu:0"):          # place variable ...
    i = tf.Variable(3)             # ... 3 on GPU 0
config = tf.ConfigProto()          # allow for soft ...
config.allow_soft_placement = True # ... placement
sess = tf.Session(config=config)   # make session ...
sess.run(i.initializer)            # ... and initialze i
